Update Dockerfile

diff --git a/pwa/Dockerfile b/pwa/Dockerfile
--- a/pwa/Dockerfile
+++ b/pwa/Dockerfile
@@ -1,77 +1,70 @@
-# syntax=docker/dockerfile:1
+# syntax=docker.io/docker/dockerfile:1
 
-# Versions
-FROM node:20-slim AS node_upstream
+FROM node:18-alpine AS node_upstream
 
-# Base stage for dev and build
+# Install dependencies only when needed
 FROM node_upstream AS base
-
-# Vérification de pourquoi libc6-compat peut être utile sur Alpine
-# https://github.com/nodejs/docker-node/tree/main#nodealpine
-#RUN apk add --no-cache libc6-compat
-
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /srv/app
 
-RUN npm install -g corepack@latest && \
-	corepack enable
+# Install dependencies based on the preferred package manager
+COPY package.json  ./
+RUN npm install;
 
-# Désactiver la télémétrie Next.js
-ENV NEXT_TELEMETRY_DISABLED 1
-
-# ============================================================
 # Development image
-# ============================================================
 FROM base AS dev
 
 EXPOSE 3000
 ENV PORT 3000
 ENV HOSTNAME localhost
 
-CMD ["sh", "-c", "npm install --legacy-peer-deps && npm run dev"]
+CMD ["sh", "-c", "npm install; npm run dev"]
 
-# ============================================================
-# Build stage
-# ============================================================
+
+# Rebuild the source code only when needed
 FROM base AS builder
-
-COPY package.json package-lock.json ./
-
-RUN npm ci --omit=dev
-
+WORKDIR /srv/app
+COPY --from=base /srv/app/node_modules ./node_modules
 COPY . .
 
-RUN npm run build
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED=1
 
-# ============================================================
-# Production image
-# ============================================================
+RUN \
+	if [ -f yarn.lock ]; then yarn run build; \
+	elif [ -f package-lock.json ]; then npm run build; \
+	elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+	else echo "Lockfile not found." && exit 1; \
+	fi
+
+# Production image, copy all the files and run next
 FROM node_upstream AS prod
-
 WORKDIR /srv/app
 
-ENV NODE_ENV production
-# Delete the following line in case you want to enable telemetry during runtime.
-ENV NEXT_TELEMETRY_DISABLED 1
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED=1
 
-# RUN addgroup --gid 1001 nodejs; \
-# 	adduser --uid 1001 nextjs
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-COPY --from=builder --link /srv/app/public ./public
-
-# Set the correct permission for prerender cache
-RUN mkdir .next; \
-	chown nextjs:nodejs .next
+COPY --from=builder /srv/app/public ./public
 
 # Automatically leverage output traces to reduce image size
 # https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --link --chown=1001:1001 /srv/app/.next/standalone ./
-COPY --from=builder --link --chown=1001:1001 /srv/app/.next/static ./.next/static
+COPY --from=builder --chown=nextjs:nodejs /srv/app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /srv/app/.next/static ./.next/static
 
 USER nextjs
 
 EXPOSE 3000
 
-ENV PORT 3000
-ENV HOSTNAME "0.0.0.0"
+ENV PORT=3000
 
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
 CMD ["node", "server.js"]
