Update Dockerfile

diff --git a/pwa/Dockerfile b/pwa/Dockerfile
--- a/pwa/Dockerfile
+++ b/pwa/Dockerfile
@@ -1,79 +1,66 @@
-# syntax=docker/dockerfile:1
+# syntax=docker.io/docker/dockerfile:1
 
-# Versions
-FROM node:lts AS node_upstream
+FROM node:18-alpine AS node_upstream
 
-# Base stage for dev and build
+# Install dependencies only when needed
 FROM node_upstream AS base
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
 
-WORKDIR /srv/app
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+	if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+	elif [ -f package-lock.json ]; then npm ci; \
+	elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+	else echo "Lockfile not found." && exit 1; \
+	fi
 
-RUN npm install -g corepack@latest && \
-	corepack enable
 
-# Désactiver la télémétrie Next.js
-ENV NEXT_TELEMETRY_DISABLED 1
-
-# ============================================================
-# Development image
-# ============================================================
-FROM base as dev
-
-WORKDIR /srv/app
-
-COPY package.json package-lock.json ./
+# Rebuild the source code only when needed
+FROM node_upstream AS builder
+WORKDIR /app
+COPY --from=base /app/node_modules ./node_modules
 COPY . .
 
-EXPOSE 3000
-ENV PORT 3000
-ENV HOSTNAME localhost
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED=1
 
-CMD ["sh", "-c", "npm install --legacy-peer-deps && npm run dev"]
+RUN \
+	if [ -f yarn.lock ]; then yarn run build; \
+	elif [ -f package-lock.json ]; then npm run build; \
+	elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+	else echo "Lockfile not found." && exit 1; \
+	fi
 
-# ============================================================
-# Build stage
-# ============================================================
-FROM base AS builder
-
-WORKDIR /srv/app
-
-COPY package.json package-lock.json ./
-RUN npm ci --omit=dev
-
-COPY . .
-
-RUN npm run build
-
-# ============================================================
 # Production image, copy all the files and run next
-# ============================================================
 FROM node_upstream AS prod
+WORKDIR /app
 
-WORKDIR /srv/app
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED=1
 
-ENV NODE_ENV production
-ENV NEXT_TELEMETRY_DISABLED 1
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-# ...existing code...
-RUN addgroup --gid 1001 nodejs && \
-	adduser --uid 1001 --gid 1001 --disabled-password --gecos "" nextjs
-# ...existing code...
-
-COPY --from=builder --link /srv/app/public ./public
-
-# Set the correct permission for prerender cache
-RUN mkdir .next && \
-	chown nextjs:nodejs .next
+COPY --from=builder /app/public ./public
 
 # Automatically leverage output traces to reduce image size
-COPY --from=builder --link --chown=1001:1001 /srv/app/.next/standalone ./
-COPY --from=builder --link --chown=1001:1001 /srv/app/.next/static ./.next/static
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
 USER nextjs
 
 EXPOSE 3000
 
-ENV PORT 3000
-ENV HOSTNAME "0.0.0.0"
+ENV PORT=3000
 
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
 CMD ["node", "server.js"]
